<a href="https://colab.research.google.com/github/kidane12/-furry-octo-potato/blob/master/Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -U gensim


Requirement already up-to-date: gensim in /usr/local/lib/python3.6/dist-packages (3.6.0)


In [4]:
!python -m gensim.scripts.make_wiki


2018-11-11 23:28:31,444 : INFO : running /usr/local/lib/python3.6/dist-packages/gensim/scripts/make_wiki.py

USAGE: make_wiki.py WIKI_XML_DUMP OUTPUT_PREFIX [VOCABULARY_SIZE]

Convert articles from a Wikipedia dump to (sparse) vectors. The input is a
bz2-compressed dump of Wikipedia articles, in XML format.

This actually creates three files:

* `OUTPUT_PREFIX_wordids.txt`: mapping between words and their integer ids
* `OUTPUT_PREFIX_bow.mm`: bag-of-words (word counts) representation, in
  Matrix Matrix format
* `OUTPUT_PREFIX_tfidf.mm`: TF-IDF representation
* `OUTPUT_PREFIX.tfidf_model`: TF-IDF model dump

The output Matrix Market files can then be compressed (e.g., by bzip2) to save
disk space; gensim's corpus iterators can work with compressed input, too.

`VOCABULARY_SIZE` controls how many of the most frequent words to keep (after
removing tokens that appear in more than 10% of all documents). Defaults to
100,000.

If you have the `pattern` package installed, this script will use

In [5]:
  python -m gensim.scripts.make_wikicorpus ~/gensim/results/enwiki-latest-pages-articles.xml.bz2 ~/gensim/results/wiki


SyntaxError: ignored

In [0]:
import numpy as np

In [6]:
a = np.array([1,2,3])
a=np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [7]:
a=np.linspace(1,12,10)
a

array([ 1.        ,  2.22222222,  3.44444444,  4.66666667,  5.88888889,
        7.11111111,  8.33333333,  9.55555556, 10.77777778, 12.        ])

In [17]:
a.reshape(5,2)

array([[ 1.        ,  2.22222222],
       [ 3.44444444,  4.66666667],
       [ 5.88888889,  7.11111111],
       [ 8.33333333,  9.55555556],
       [10.77777778, 12.        ]])

In [3]:
a.shape

NameError: ignored

In [8]:
a*3

array([ 3.        ,  6.66666667, 10.33333333, 14.        , 17.66666667,
       21.33333333, 25.        , 28.66666667, 32.33333333, 36.        ])

In [11]:
np.random.random((2,3))

array([[0.59431041, 0.48505042, 0.91379739],
       [0.71731849, 0.79504114, 0.30634871]])

# New Section

In [16]:
a.var()

12.324074074074076

In [33]:
a=np.loadtxt('cluster00_100_2_2.dat',dtype=np.str, delimiter=';', skiprows=1,usecols =(0,1))
a

array([['0.7858218914665223', '0.9506279201197162'],
       ['0.8891222824568827', '0.5866023549685591'],
       ['0.8009481241821915', '0.919178705136175'],
       ['0.7180951541691747', '0.9879223305266862'],
       ['1.2779285285991637', '0.8119032323121382'],
       ['0.7710071720551247', '0.5916433434333311'],
       ['1.1492305737354078', '0.8231967128313816'],
       ['1.241507922879664', '0.9654752619462502'],
       ['0.6215365949803924', '1.013451397322168'],
       ['0.3932403647558615', '0.5359616142079897'],
       ['1.0707252825952518', '0.7067109520106308'],
       ['0.9665627760219125', '0.6142332465571857'],
       ['1.0348061275064921', '0.8575843367827801'],
       ['0.41917967263287165', '0.8875768776651289'],
       ['0.7525671949411257', '0.7237976820144686'],
       ['0.8414795494628673', '0.8326699973370882'],
       ['0.9586815606039837', '1.0342342924312062'],
       ['0.956412583158689', '0.6846398077588424'],
       ['0.9085112778112926', '0.7752455995499019

In [0]:
y = a.astype(np.float)

In [35]:
y

array([[ 0.78582189,  0.95062792],
       [ 0.88912228,  0.58660235],
       [ 0.80094812,  0.91917871],
       [ 0.71809515,  0.98792233],
       [ 1.27792853,  0.81190323],
       [ 0.77100717,  0.59164334],
       [ 1.14923057,  0.82319671],
       [ 1.24150792,  0.96547526],
       [ 0.62153659,  1.0134514 ],
       [ 0.39324036,  0.53596161],
       [ 1.07072528,  0.70671095],
       [ 0.96656278,  0.61423325],
       [ 1.03480613,  0.85758434],
       [ 0.41917967,  0.88757688],
       [ 0.75256719,  0.72379768],
       [ 0.84147955,  0.83267   ],
       [ 0.95868156,  1.03423429],
       [ 0.95641258,  0.68463981],
       [ 0.90851128,  0.7752456 ],
       [ 0.76998434,  1.06476886],
       [ 0.77138195,  0.81698818],
       [ 0.54543326,  0.89531472],
       [ 0.93933933,  0.86892166],
       [ 0.69102608,  1.18314546],
       [ 0.84515174,  0.6537506 ],
       [ 0.84085594,  0.64411448],
       [ 0.43805571,  0.62900545],
       [ 0.82098533,  0.77486508],
       [ 1.12306918,

In [39]:
a[1:]

array([['0.8891222824568827', '0.5866023549685591'],
       ['0.8009481241821915', '0.919178705136175'],
       ['0.7180951541691747', '0.9879223305266862'],
       ['1.2779285285991637', '0.8119032323121382'],
       ['0.7710071720551247', '0.5916433434333311'],
       ['1.1492305737354078', '0.8231967128313816'],
       ['1.241507922879664', '0.9654752619462502'],
       ['0.6215365949803924', '1.013451397322168'],
       ['0.3932403647558615', '0.5359616142079897'],
       ['1.0707252825952518', '0.7067109520106308'],
       ['0.9665627760219125', '0.6142332465571857'],
       ['1.0348061275064921', '0.8575843367827801'],
       ['0.41917967263287165', '0.8875768776651289'],
       ['0.7525671949411257', '0.7237976820144686'],
       ['0.8414795494628673', '0.8326699973370882'],
       ['0.9586815606039837', '1.0342342924312062'],
       ['0.956412583158689', '0.6846398077588424'],
       ['0.9085112778112926', '0.7752455995499019'],
       ['0.7699843366823993', '1.0647688604796792